# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-25 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0007_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='buying_type',
            field=models.CharField(choices=[('Self', 'Self'), ('Delivery', 'Delivery')], default='Self', max_length=40),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Received for processing', 'Received for processing'), ('Processing', 'Processing'), ('Payed', 'Payed')], default='Received for processing', max_length=100),
        ),
    ]
